export enum PresetTheme {
  GREEN = 'green',
  RED = 'red',
  PURPLE = 'purple',
  BLUE = 'blue',
  YELLOW = 'yellow',
  CYAN = 'cyan',
  DARK_GREEN = 'dark_green',
  YELLOW_WINE = 'yellow_wine',
  PINK = 'pink',
  SUNSET = 'sunset',
  NATIVE = 'native',
  PURPLE_NEBULA = 'purple_nebula',
  BLUE_ORBIT = 'blue_orbit',
  SUNSET_EMBER = 'sunset_ember',
  TEAL_LAGOON = 'teal_lagoon',
  ROSE_PULSE = 'rose_pulse',
  AMBER_FORGE = 'amber_forge',
  EMERALD_CANOPY = 'emerald_canopy',
  CYAN_DEPTH = 'cyan_depth',
  INDIGO_NIGHT = 'indigo_night',
  MONO_SLATE = 'mono_slate',
  NEON_HORIZON = 'neon_horizon',
  AURORA_DRIFT = 'aurora_drift',
  LAVA_SURGE = 'lava_surge',
  FROST_BYTE = 'frost_byte',
  ACID_RAIN = 'acid_rain',
}
