export const presets = [
  {
    chart: 'calendar',
    gap: 0.6,
    scale: 2,
    weeks: 15,
    dark: false,
  },

  {
    chart: '3dbar',
    gap: 0.6,
    scale: 2,
    gradient: false,
    flatten: '0',
    format: '',
    quality: 1,
    weeks: 30,
    dark: false,
    theme: 'green',
  },

  {
    chart: '3dbar',
    gap: 0.6,
    scale: 2,
    gradient: false,
    flatten: '1',
    format: '',
    quality: 1,
    weeks: 30,
    dark: false,
    theme: 'green',
  },

  {
    chart: '3dbar',
    gap: 0.6,
    scale: 2,
    gradient: false,
    flatten: '2',
    animation: 'fall',
    animation_duration: '2',
    animation_delay: '0.005',
    weeks: 30,
    theme: 'green',
  },

  {
    chart: '3dbar',
    gap: 0.6,
    scale: 2,
    gradient: false,
    flatten: '1',
    animation: 'wave',
    animation_duration: '4',
    animation_delay: '0.06',
    animation_amplitude: 24,
    animation_frequency: '0.1',
    animation_wave_center: '0_3',
    weeks: 30,
    dark: true,
    theme: 'green',
    animation_loop: true,
    animation_reverse: false,
  },

  {
    chart: '3dbar',
    gap: 0.6,
    scale: 2,
    gradient: false,
    flatten: '1',
    animation: 'wave',
    animation_duration: '1',
    animation_delay: '0.05',
    animation_amplitude: '20',
    animation_frequency: '0.5',
    animation_wave_center: '0_0',
    weeks: 30,
    dark: true,
    theme: 'green',
    animation_loop: true,
    animation_reverse: false,
  },

  {
    chart: '3dbar',
    gap: 0.6,
    scale: 2,
    gradient: false,
    flatten: '2',
    animation: 'wave',
    animation_duration: '1',
    animation_delay: '0.05',
    animation_amplitude: '20',
    animation_frequency: '0.5',
    animation_wave_center: '10_0',
    weeks: 30,
    dark: false,
    theme: 'green',
    animation_loop: true,
    animation_reverse: false,
  },

  {
    chart: '3dbar',
    gap: 0.6,
    scale: 2,
    gradient: false,
    flatten: '1',
    animation: 'mess',
    animation_duration: '4',
    animation_delay: '0.06',
    animation_amplitude: 24,
    animation_frequency: '0.1',
    animation_wave_center: '0_3',
    weeks: 30,
    dark: true,
    theme: 'green',
    animation_loop: true,
    animation_reverse: false,
  },
];
